/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as OverseerRouteImport } from './routes/overseer'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SermonsIdRouteImport } from './routes/sermons.$id'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSermonsRouteImport } from './routes/admin.sermons'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLivestreamRouteImport } from './routes/admin.livestream'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'

const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const OverseerRoute = OverseerRouteImport.update({
  id: '/overseer',
  path: '/overseer',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SermonsIdRoute = SermonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SermonsRoute,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GalleryRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivestreamRoute = AdminLivestreamRouteImport.update({
  id: '/livestream',
  path: '/livestream',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/live': typeof LiveRoute
  '/overseer': typeof OverseerRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/livestream': typeof AdminLivestreamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/live': typeof LiveRoute
  '/overseer': typeof OverseerRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/livestream': typeof AdminLivestreamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/live': typeof LiveRoute
  '/overseer': typeof OverseerRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/livestream': typeof AdminLivestreamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/overseer'
    | '/sermons'
    | '/admin/admins'
    | '/admin/gallery'
    | '/admin/livestream'
    | '/admin/login'
    | '/admin/quotes'
    | '/admin/sermons'
    | '/admin/settings'
    | '/gallery/$id'
    | '/quote/$id'
    | '/sermons/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/overseer'
    | '/sermons'
    | '/admin/admins'
    | '/admin/gallery'
    | '/admin/livestream'
    | '/admin/login'
    | '/admin/quotes'
    | '/admin/sermons'
    | '/admin/settings'
    | '/gallery/$id'
    | '/quote/$id'
    | '/sermons/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/live'
    | '/overseer'
    | '/sermons'
    | '/admin/admins'
    | '/admin/gallery'
    | '/admin/livestream'
    | '/admin/login'
    | '/admin/quotes'
    | '/admin/sermons'
    | '/admin/settings'
    | '/gallery/$id'
    | '/quote/$id'
    | '/sermons/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  LiveRoute: typeof LiveRoute
  OverseerRoute: typeof OverseerRoute
  SermonsRoute: typeof SermonsRouteWithChildren
  QuoteIdRoute: typeof QuoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overseer': {
      id: '/overseer'
      path: '/overseer'
      fullPath: '/overseer'
      preLoaderRoute: typeof OverseerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sermons/$id': {
      id: '/sermons/$id'
      path: '/$id'
      fullPath: '/sermons/$id'
      preLoaderRoute: typeof SermonsIdRouteImport
      parentRoute: typeof SermonsRoute
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livestream': {
      id: '/admin/livestream'
      path: '/livestream'
      fullPath: '/admin/livestream'
      preLoaderRoute: typeof AdminLivestreamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLivestreamRoute: typeof AdminLivestreamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSermonsRoute: typeof AdminSermonsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLivestreamRoute: AdminLivestreamRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSermonsRoute: AdminSermonsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GalleryRouteChildren {
  GalleryIdRoute: typeof GalleryIdRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIdRoute: GalleryIdRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface SermonsRouteChildren {
  SermonsIdRoute: typeof SermonsIdRoute
}

const SermonsRouteChildren: SermonsRouteChildren = {
  SermonsIdRoute: SermonsIdRoute,
}

const SermonsRouteWithChildren =
  SermonsRoute._addFileChildren(SermonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRouteWithChildren,
  LiveRoute: LiveRoute,
  OverseerRoute: OverseerRoute,
  SermonsRoute: SermonsRouteWithChildren,
  QuoteIdRoute: QuoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
